### ISSUE TITLE
Bug in the update 1.5.10 [Forge 1.20.1]

### ISSUE THREAD

**Issue by Bruskych** [juancarloscp52/spyglass-improvements#86]
The Spyglass zoom no longer works when it's in the Kurios slot or when using it in Creative Mode. Zoom will only work when holding it in your hand.

Please fix this

**Comment by juancarloscp52** [comment]
Hi! are you using any other mods? if so, which ones? I can't seem to replicate it

**Comment by juancarloscp52** [comment]
also what specific forge version are you using?

**Comment by Bruskych** [comment]
> Hi! are you using any other mods? if so, which ones? I can't seem to replicate it

I use Forge 47.4.0
And mod:
  usefulspyglass-forge-1.20.1-1.0.0

I also have many other mods, but they're not related to the spyglass.
And regarding optimization:
Embeddium, Chloride and others

**Comment by Bruskych** [comment]
I tested it, it's the mod's fault: usefulspyglass-forge-1.20.1-1.0.0

**Comment by juancarloscp52** [comment]
I can confirm. Its because they are using an "invasive" mixin on their mod versions <=1.20.1. Spyglass improvements used exactly the same invasive method until this last version (which is a backport of the current MCs versions) so now their mod is taking preference over how zoom is being applied.

I've tried to force compatibiliy from my part, but without changing my mixin to a more invasive one (not recomended for compatibiliy with other mods), its not posible.

I will open an issue on their github with some info and hopefully their mod get updated.

**Comment by juancarloscp52** [comment]
Issue created (https://github.com/BrokenK3yboard/UsefulSpyglass/issues/26), while the issue is fixed, you'll have to disable one of the two mods or downgrade to the previous version.

**Comment by Bruskych** [comment]
> Issue created ([BrokenK3yboard/UsefulSpyglass#26](https://github.com/BrokenK3yboard/UsefulSpyglass/issues/26)), while the issue is fixed, you'll have to disable one of the two mods or downgrade to the previous version.

I understand you, thank you for your work and quick response!

**Comment by Bruskych** [comment]
After updating two mods to the latest version, the bug persists. Now, even when holding the telescope in hand, the zoom doesn't work.
